#!/usr/bin/env python3
"""Generate Localizable.xcstrings for SANKET."""
import json

# key -> (en, hi)
STRINGS = {
    "app_name": ("SANKET", "संकेत"),
    "tab_home": ("Home", "होम"),
    "tab_opportunities": ("Opportunities", "अवसर"),
    "tab_skills": ("My Skills", "मेरे कौशल"),
    "tab_training": ("Training", "प्रशिक्षण"),
    "tab_jobs": ("Jobs", "नौकरियाँ"),
    "profile_title": ("Profile", "प्रोफ़ाइल"),
    "cta_continue": ("Continue", "जारी रखें"),
    "cta_close": ("Close", "बंद करें"),
    "cta_cancel": ("Cancel", "रद्द करें"),
    "cta_create_profile": ("Create profile", "प्रोफ़ाइल बनाएँ"),
    "cta_start_assessment": ("Start assessment", "आकलन शुरू करें"),
    "cta_view_path": ("View Path", "मार्ग देखें"),
    "cta_start_training": ("Start Training", "प्रशिक्षण शुरू करें"),
    "cta_continue_training": ("Continue Training", "प्रशिक्षण जारी रखें"),
    "cta_view_jobs": ("View jobs", "नौकरियाँ देखें"),
    "cta_view_application": ("View Application", "आवेदन देखें"),
    "cta_view_outcome": ("View outcome", "परिणाम देखें"),
    "cta_improve_profile": ("Improve Profile", "प्रोफ़ाइल सुधारें"),
    "cta_explore_opportunities": ("Explore Opportunities", "अवसर देखें"),
    "cta_start_transition": ("Start Transition", "परिवर्तन शुरू करें"),
    "cta_compare": ("Compare", "तुलना करें"),
    "cta_enrol": ("Enrol", "नामांकन करें"),
    "cta_confirm_enrol": ("Confirm enrolment", "नामांकन पुष्टि करें"),
    "cta_apply": ("Apply", "आवेदन करें"),
    "cta_confirm_apply": ("Confirm apply", "आवेदन पुष्टि करें"),
    "cta_view_skill_progress": ("View skill progress", "कौशल प्रगति देखें"),
    "cta_complete_certification": ("Complete certification", "प्रमाणपत्र पूरा करें"),
    "cta_submit_outcome": ("Submit", "जमा करें"),
    "cta_skip": ("Skip", "छोड़ें"),
    "nba_continue": ("Continue", "जारी रखें"),
    "onboarding_header": ("Build skills for where the economy is going.", "अर्थव्यवस्था की दिशा के लिए कौशल बनाएँ।"),
    "onboard_q_name": ("What should we call you?", "हम आपको क्या कहें?"),
    "onboard_q_location": ("Where do you work today?", "आप आज कहाँ काम करते हैं?"),
    "onboard_q_age": ("Which age band are you in?", "आप किस आयु वर्ग में हैं?"),
    "onboard_q_education": ("What is your highest education?", "आपकी उच्चतम शिक्षा क्या है?"),
    "onboard_q_occupation": ("What is your current occupation?", "आपका वर्तमान पेशा क्या है?"),
    "onboard_q_experience": ("How many years of experience?", "कितने वर्षों का अनुभव?"),
    "onboard_q_languages": ("Which languages do you use at work?", "काम पर आप कौन-सी भाषाएँ उपयोग करते हैं?"),
    "onboard_name_placeholder": ("Your name", "आपका नाम"),
    "years_short": ("years", "वर्ष"),
    "years_count %lld": ("%lld years", "%lld वर्ष"),
    "greeting_morning": ("Good morning, %@", "सुप्रभात, %@"),
    "greeting_afternoon": ("Good afternoon, %@", "नमस्कार, %@"),
    "greeting_evening": ("Good evening, %@", "शुभ संध्या, %@"),
    "nba_onboarding_title": ("Finish setting up", "सेटअप पूरा करें"),
    "nba_onboarding_sub": ("A short profile helps us suggest the right next step.", "संक्षिप्त प्रोफ़ाइल सही अगला कदम सुझाती है।"),
    "nba_profiled_title": ("Check your skills", "अपने कौशल जाँचें"),
    "nba_profiled_sub": ("A short assessment clarifies what is verified and what is estimated.", "छोटा आकलन स्पष्ट करता है क्या सत्यापित है और क्या अनुमानित।"),
    "nba_opportunity_title": ("Your next opportunity", "आपका अगला अवसर"),
    "nba_opportunity_sub": ("EV Technician · %lld%% match · %lld skills to develop · %lld-week path", "EV Technician · %lld%% मेल · %lld कौशल विकसित करें · %lld-सप्ताह मार्ग"),
    "nba_transition_title": ("Start your training path", "अपना प्रशिक्षण मार्ग शुरू करें"),
    "nba_transition_sub": ("Courses chosen to close your EV Technician skill gap.", "EV Technician कौशल अंतर भरने वाले पाठ्यक्रम।"),
    "nba_enrolled_title": ("Training has started", "प्रशिक्षण शुरू हो चुका है"),
    "nba_enrolled_sub": ("Today: %@", "आज: %@"),
    "nba_training_title": ("Keep going", "आगे बढ़ते रहें"),
    "nba_training_sub": ("Week %lld of %lld · %@ today", "सप्ताह %lld / %lld · आज %@"),
    "nba_certified_title": ("You're ready to apply", "आप आवेदन के लिए तैयार हैं"),
    "nba_certified_sub": ("EV Technician fit is now %lld%% after certification.", "प्रमाणपत्र के बाद EV Technician मेल अब %lld%% है।"),
    "nba_applied_title": ("You're shortlisted", "आप शॉर्टलिस्ट हैं"),
    "nba_applied_sub": ("You're shortlisted at Pragati Electric Mobility", "आप Pragati Electric Mobility में शॉर्टलिस्ट हैं"),
    "nba_placed_title": ("You're placed", "आप नियुक्त हैं"),
    "nba_placed_sub": ("Congratulations on joining as an EV Technician.", "EV Technician के रूप में शामिल होने पर बधाई।"),
    "stat_training_active": ("Training active", "सक्रिय प्रशिक्षण"),
    "stat_jobs_matched": ("Jobs matched", "मिलती नौकरियाँ"),
    "stat_skill_progress": ("Skill progress", "कौशल प्रगति"),
    "stat_certifications": ("Certifications", "प्रमाणपत्र"),
    "section_near_you": ("Near you", "आपके पास"),
    "near_you_meta %lld %lld": ("%lld%% fit · %lld km", "%lld%% मेल · %lld किमी"),
    "section_skills": ("Skills", "कौशल"),
    "section_your_skills": ("Your skills", "आपके कौशल"),
    "section_privacy": ("Privacy", "गोपनीयता"),
    "section_language": ("Language", "भाषा"),
    "section_scores": ("Scores", "अंक"),
    "section_build_next": ("Build next", "आगे बनाएँ"),
    "section_my_training": ("My training", "मेरा प्रशिक्षण"),
    "section_recommendations": ("Recommendations", "सिफ़ारिशें"),
    "section_courses": ("Courses for your gap", "आपके अंतर के पाठ्यक्रम"),
    "section_modules": ("Modules", "मॉड्यूल"),
    "section_tracks": ("Tracks", "ट्रैक"),
    "badge_verified": ("Verified", "सत्यापित"),
    "badge_estimated": ("Estimated", "अनुमानित"),
    "fit_percent %lld": ("%lld%% fit", "%lld%% मेल"),
    "estimated_explainer": ("Estimated skills become Verified after an assessment or certificate.", "अनुमानित कौशल आकलन या प्रमाणपत्र के बाद सत्यापित होते हैं।"),
    "profile_certs %lld": ("%lld certifications", "%lld प्रमाणपत्र"),
    "profile_training %lld": ("%lld trainings", "%lld प्रशिक्षण"),
    "profile_complete": ("Profile complete", "प्रोफ़ाइल पूर्ण"),
    "privacy_share_employers": ("Share profile with employers", "नियोक्ताओं के साथ प्रोफ़ाइल साझा करें"),
    "privacy_training_recs": ("Use profile for training recommendations", "प्रशिक्षण सिफ़ारिशों के लिए प्रोफ़ाइल उपयोग करें"),
    "privacy_note": ("You control who sees your profile.", "आप तय करते हैं कि आपकी प्रोफ़ाइल कौन देखे।"),
    "sample_data_label": ("Sample data – synthetic", "नमूना डेटा – सिंथेटिक"),
    "presenter_controls_title": ("Presenter controls", "प्रस्तोता नियंत्रण"),
    "presenter_jump_stage": ("Jump to stage", "चरण पर जाएँ"),
    "presenter_advance_application": ("Advance main application", "मुख्य आवेदन आगे बढ़ाएँ"),
    "presenter_advance_training": ("Advance training progress", "प्रशिक्षण प्रगति बढ़ाएँ"),
    "presenter_reset": ("Reset journey", "यात्रा रीसेट करें"),
    "journey_title": ("My Workforce Journey", "मेरी कार्यबल यात्रा"),
    "journey_intro": ("Where you started and how far you have come.", "आप कहाँ से शुरू हुए और कितनी दूर आए।"),
    "journey_started": ("Starting point", "प्रारंभ बिंदु"),
    "journey_bridge": ("Bridge training", "ब्रिज प्रशिक्षण"),
    "journey_target_role": ("Target role", "लक्ष्य भूमिका"),
    "journey_certification": ("Certification", "प्रमाणपत्र"),
    "journey_job": ("Job", "नौकरी"),
    "journey_future": ("Future skills", "भविष्य के कौशल"),
    "journey_future_skills": ("Suggested next skills", "सुझाए गए अगले कौशल"),
    "skill_map_title": ("My Skill Map", "मेरा कौशल मानचित्र"),
    "assessment_title": ("Skill Assessment", "कौशल आकलन"),
    "assess_q_plc": ("How familiar are you with PLC systems?", "PLC प्रणालियों से आप कितने परिचित हैं?"),
    "assess_q_automation": ("How familiar are you with automation on the shop floor?", "शॉप फ्लोर ऑटोमेशन से आप कितने परिचित हैं?"),
    "assess_q_motor": ("How comfortable are you with motor control work?", "मोटर नियंत्रण कार्य में आप कितने सहज हैं?"),
    "assess_q_battery": ("How familiar are you with battery basics?", "बैटरी की बुनियादी बातों से आप कितने परिचित हैं?"),
    "assess_q_diag": ("How often do you use diagnostic tools?", "आप डायग्नोस्टिक उपकरण कितनी बार उपयोग करते हैं?"),
    "assess_opt_beginner": ("Beginner", "शुरुआती"),
    "assess_opt_working": ("Working knowledge", "कार्यकारी ज्ञान"),
    "assess_opt_advanced": ("Advanced", "उन्नत"),
    "assess_result_range %@": ("Estimated proficiency %@", "अनुमानित दक्षता %@"),
    "assess_result_confidence %@": ("Confidence: %@", "विश्वास: %@"),
    "assess_result_based": ("Based on: work history + certification", "आधार: कार्य इतिहास + प्रमाणपत्र"),
    "assess_done_title": ("Assessment saved", "आकलन सहेजा गया"),
    "assess_done_body": ("Estimated skills are marked clearly until verified.", "सत्यापित होने तक अनुमानित कौशल स्पष्ट रूप से चिह्नित हैं।"),
    "confidence_low": ("Low", "कम"),
    "confidence_medium": ("Medium", "मध्यम"),
    "confidence_high": ("High", "उच्च"),
    "filter_all": ("All", "सभी"),
    "filter_near_me": ("Near me", "मेरे पास"),
    "filter_short_training": ("Short training", "छोटा प्रशिक्षण"),
    "filter_high_demand": ("High demand", "उच्च माँग"),
    "demand_outlook %@": ("Demand outlook: %@", "माँग दृष्टिकोण: %@"),
    "opportunity_meta %lld %lld": ("%lld km away · %lld-week transition", "%lld किमी दूर · %lld-सप्ताह परिवर्तन"),
    "skills_missing %@": ("Skills missing: %@", "कमी कौशल: %@"),
    "why_opportunity": ("Why this opportunity?", "यह अवसर क्यों?"),
    "transition_title": ("Career Transition", "करियर परिवर्तन"),
    "today_label": ("Today", "आज"),
    "target_label": ("Target", "लक्ष्य"),
    "bridge_caption": ("A clear path from today's role to the target role.", "आज की भूमिका से लक्ष्य भूमिका तक स्पष्ट मार्ग।"),
    "already_have": ("Already have", "पहले से हैं"),
    "to_develop": ("To develop", "विकसित करें"),
    "path_details": ("Path details", "मार्ग विवरण"),
    "detail_training": ("Training", "प्रशिक्षण"),
    "detail_centre": ("Nearest centre", "निकटतम केंद्र"),
    "detail_cost": ("Course cost", "पाठ्यक्रम लागत"),
    "detail_demand": ("Employer demand", "नियोक्ता माँग"),
    "detail_salary": ("Expected salary", "अपेक्षित वेतन"),
    "compare_paths": ("Compare paths", "मार्गों की तुलना"),
    "weeks_unit": ("weeks", "सप्ताह"),
    "training_recs_title": ("Training for you", "आपके लिए प्रशिक्षण"),
    "training_reason": ("Recommended because these modules close your current skill gap for EV Technician.", "इन मॉड्यूल से EV Technician का वर्तमान कौशल अंतर भरता है।"),
    "course_meta %lld %lld": ("%lld weeks · %lld km", "%lld सप्ताह · %lld किमी"),
    "closes_gap %@": ("Closes gap: %@", "अंतर भरता है: %@"),
    "based_on": ("Based on", "आधारित"),
    "based_skills": ("Current skills", "वर्तमान कौशल"),
    "based_target": ("Target role", "लक्ष्य भूमिका"),
    "based_gap": ("Skill gap", "कौशल अंतर"),
    "based_seats": ("Seat availability", "सीट उपलब्धता"),
    "based_location": ("Location", "स्थान"),
    "based_duration": ("Duration", "अवधि"),
    "based_demand": ("Demand", "माँग"),
    "centres_title": ("Training centres", "प्रशिक्षण केंद्र"),
    "centre_details": ("Centre details", "केंद्र विवरण"),
    "seats_available": ("Seats available", "उपलब्ध सीटें"),
    "seats_available_label %lld": ("%lld seats available", "%lld सीटें उपलब्ध"),
    "next_batch": ("Next batch", "अगला बैच"),
    "equipment_yes": ("Equipment available", "उपकरण उपलब्ध"),
    "equipment_no": ("Equipment limited", "उपकरण सीमित"),
    "placement_yes": ("Placement linkage available", "प्लेसमेंट लिंकेज उपलब्ध"),
    "placement_no": ("No placement linkage", "प्लेसमेंट लिंकेज नहीं"),
    "enrol_confirm_title": ("Enrol in this programme?", "इस कार्यक्रम में नामांकन?"),
    "enrol_confirm_body": ("You will start the EV Technician training journey.", "आप EV Technician प्रशिक्षण यात्रा शुरू करेंगे।"),
    "training_journey_title": ("Training journey", "प्रशिक्षण यात्रा"),
    "training_week_header": ("Week %lld of %lld", "सप्ताह %lld / %lld"),
    "training_percent": ("%lld%% completed", "%lld%% पूरा"),
    "track_attendance": ("Attendance", "उपस्थिति"),
    "track_assignments": ("Assignments", "असाइनमेंट"),
    "track_assessments": ("Assessments", "आकलन"),
    "track_certification": ("Certification", "प्रमाणपत्र"),
    "cert_pending": ("Pending", "लंबित"),
    "cert_complete": ("Complete", "पूर्ण"),
    "skill_progress_title": ("Skill progress", "कौशल प्रगति"),
    "skill_progress_intro": ("Before and after your bridge training.", "ब्रिज प्रशिक्षण से पहले और बाद।"),
    "before_label": ("Before", "पहले"),
    "after_label": ("After", "बाद"),
    "cert_completed_message": ("Certification completed. Your workforce profile has been updated.", "प्रमाणपत्र पूरा। आपकी कार्यबल प्रोफ़ाइल अपडेट हो गई है।"),
    "jobs_matches": ("Matches", "मेल"),
    "jobs_applications": ("Applications", "आवेदन"),
    "required_skills": ("Required skills", "आवश्यक कौशल"),
    "why_matched": ("Why am I matched?", "मुझसे मेल क्यों?"),
    "why_apply_now %@": ("Why apply now? %@", "अभी आवेदन क्यों? %@"),
    "apply_confirm_title": ("Apply to this role?", "इस भूमिका के लिए आवेदन?"),
    "apply_confirm_body %@": ("Send your profile to %@.", "%@ को अपनी प्रोफ़ाइल भेजें।"),
    "applications_empty_title": ("No applications yet", "अभी कोई आवेदन नहीं"),
    "applications_empty_body": ("When you apply to a match, it appears here.", "जब आप मेल पर आवेदन करेंगे, वह यहाँ दिखेगा।"),
    "status_applied": ("Applied", "आवेदित"),
    "status_shortlisted": ("Shortlisted", "शॉर्टलिस्ट"),
    "status_interview": ("Interview", "साक्षात्कार"),
    "status_selected": ("Selected", "चयनित"),
    "status_joined": ("Joined", "शामिल"),
    "outcome_title": ("Workforce outcome", "कार्यबल परिणाम"),
    "outcome_congrats": ("Congratulations! You joined as an EV Technician.", "बधाई! आप EV Technician के रूप में शामिल हुए।"),
    "outcome_stats": ("Skills added 3 · Certification 1 · Employment active", "कौशल जुड़े 3 · प्रमाणपत्र 1 · रोजगार सक्रिय"),
    "outcome_optional_form": ("Optional update", "वैकल्पिक अपडेट"),
    "outcome_employment": ("Employment status", "रोजगार स्थिति"),
    "outcome_role": ("Role", "भूमिका"),
    "outcome_joining": ("Joining date", "जॉइनिंग तिथि"),
    "outcome_wage": ("Wage band", "वेतन बैंड"),
    "outcome_still_working": ("Still working after 3 months?", "3 महीने बाद भी काम कर रहे हैं?"),
    "outcome_consent_note": ("This helps improve recommendations for other workers. You can skip.", "इससे अन्य कामगारों के लिए सिफ़ारिशें बेहतर होती हैं। आप छोड़ सकते हैं।"),
    "outcome_thanks": ("Thanks. Your update was saved.", "धन्यवाद। आपका अपडेट सहेजा गया।"),
}

def unit(value):
    return {"stringUnit": {"state": "translated", "value": value}}

catalog = {
    "sourceLanguage": "en",
    "strings": {},
    "version": "1.0",
}

for key, (en, hi) in STRINGS.items():
    catalog["strings"][key] = {
        "extractionState": "manual",
        "localizations": {
            "en": unit(en),
            "hi": unit(hi),
        },
    }

path = "/Users/sukhvirsingh/webdev/SANKET/SANKET/Resources/Localizable.xcstrings"
with open(path, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"Wrote {len(STRINGS)} strings to {path}")
